[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["synve"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.1"
colored = "2.0.0"
itertools = "0.9.0"
nom = "7.1.3"
regex = "1"